version: "3.5"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: calendar
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: unless-stopped

  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 1234@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    restart: unless-stopped
