version: '3.5'

services:
  database:
    build: database
    ports:
      - 5432:5432
    environment:
      DB_USER: me
      DB_PASSWORD: 1234
      DB_NAME: calendar
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database/data:/var/lib/postgresql/data
    restart: unless-stopped

  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - '8000:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 1234@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - ./database/pgadmin:/var/lib/pgadmin
    restart: unless-stopped
